receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  logzio:
    account_token: "ZTVNvSMnMWJOpuDnUIuRHBmtIObWmaHX"
    region: "us"
    headers:
      user-agent: logzio-opentelemetry-traces

processors:
  batch:

service:
  extensions: []
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logzio ]
  telemetry:
    logs:
      level: debug